Update .github/workflows/reusable-ruff.yml
Co-authored-by: Jake Herrmann <jtherrmann@alaska.edu>

diff --git a/.github/workflows/reusable-ruff.yml b/.github/workflows/reusable-ruff.yml
--- a/.github/workflows/reusable-ruff.yml
+++ b/.github/workflows/reusable-ruff.yml
@@ -23,4 +23,4 @@ jobs:
 
       # To automatically fix errors, run `ruff format .`
       - name: Ruff format check
-        run: ruff format .
+        run: ruff format --diff . || echo 'To automatically fix errors, run `ruff format .`'
