revise ruff failure handling

diff --git a/.github/workflows/reusable-ruff.yml b/.github/workflows/reusable-ruff.yml
--- a/.github/workflows/reusable-ruff.yml
+++ b/.github/workflows/reusable-ruff.yml
@@ -19,11 +19,7 @@ jobs:
 
       - name: ruff check
         id: ruff_check
-        run: ruff check --output-format=github .
-
-      - name: ruff check failure
-        if: ${{ failure() && steps.ruff_check.conclusion == 'failure' }}
-        run: echo 'To automatically fix errors, run `ruff check --fix .`' && exit 1
+        run: ruff check --output-format=github . || (echo 'To automatically fix errors, run `ruff check --fix .`' && exit 1)
 
       - name: ruff format
         id: ruff_format
